export enum RoutesPath {
  HOME = "/",
  ABOUT_US = "/about",
  SHIRTS = "/shirts",
  APPLICATION = "/application",
  LOG_IN = "/log-in",
  REGISTRATION = "/registration",
  SMART_CHAIR = "/smart-chair",
  PROJECTS_UE ="/projects-ue",
  PROFILE_USER = "/profile/user/",
  YOUR_SHIRT = "/profile/user/shirt",
  TRAINING = "/profile/user/training",
  STATISTICS = "/profile/user/statistic",
  TRAINING_PLAN = "/profile/user/training-plan",

  PROFILE_TRAINER = "/profile/trainer/",
  SETTINGS = "/profile/user/settings",
  REQUESTS = "/profile/trainer/requests",
  CLIENTS = "/profile/trainer/clients",
  OPINIONS = "/profile/trainer/opinions",
  SEE_STATISTICS = "/profile/trainer/see-statistic/",
  LEAVE_REVIEW = "/profile/trainer/leave-review/",
  SEE_TRAINING_DONE = "/profile/trainer/clients/see-trainings/",
}
